"""Assemble the Figure 7 Supplementary materials into one folder with
collision-free, S-labelled names. Tumor-only scope. Copies from this package's
cached pipeline outputs (tusc2_deg/{nk,cd8}/output); the canonical outputs are
not moved.

The effect-size ladder (S2) and curated-label provenance (S4) are single
multi-context TSVs; for the tumor-only Supplementary set they are FILTERED to the
tumor context on copy (NK Tang_Tumor, CD8 CD8_TIL). The canonical pipeline
outputs are left untouched.

Run:  python collect_supplementary.py
Out:  supplementary/  (+ README.md mapping files to Suppl. labels)
"""
from __future__ import annotations
import shutil
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))               # import this folder's tusc2_deg package
from tusc2_deg.nk import config as nkc       # noqa: E402
from tusc2_deg.cd8 import config as cdc       # noqa: E402

OUT = HERE / "supplementary"
LINEAGES = [("NK", nkc, "Tang_Tumor"), ("CD8", cdc, "CD8_TIL")]

# (suppl label, description, src_path_fn(cfg, ctx) -> Path, dst_name_fn(lineage) -> str,
#  tumor_only: filter a multi-context TSV to the tumor context before shipping)
SPECS = [
    ("Suppl. Data S1",  "Per-gene differential expression (DESeq2 pseudobulk)",
     lambda c, x: c.DEG_DIR / f"deg_pseudobulk_{x}.csv",
     lambda L: f"SupplData_S1_{L}_per_gene_DE.csv", False),
    ("Suppl. Data S2", "Effect-size ladder + calibrated 1.1-fold-null (n_calibrated_sig_floored)",
     lambda c, x: c.AUDIT_DIR / "deg_sig_ladder.tsv",
     lambda L: f"SupplData_S2_{L}_effect_size_ladder.tsv", True),
    ("Suppl. Data S3",  "GSEA preranked output (res2d)",
     lambda c, x: c.GSEA_DIR / f"gsea_{x}.csv",
     lambda L: f"SupplData_S3_{L}_GSEA.csv", False),
    ("Suppl. Data S4",  "Curated-label provenance (family + gate tag)",
     lambda c, x: c.AUDIT_DIR / "curated_label_provenance.tsv",
     lambda L: f"SupplData_S4_{L}_curated_label_provenance.tsv", True),
]


def _emit(src: Path, dst: Path, tumor_only: bool, ctx: str) -> str:
    """Copy src->dst, or (tumor_only) write only the rows whose context == ctx.
    Leaves the canonical pipeline output untouched; only the shipped copy is
    filtered to the tumor context."""
    if not tumor_only:
        shutil.copy2(src, dst)
        return "copied"
    df = pd.read_csv(src, sep="\t")
    if "context" not in df.columns:
        raise SystemExit(f"tumor_only set but no 'context' column in {src}")
    sub = df[df["context"] == ctx]
    if sub.empty:
        raise SystemExit(
            f"tumor filter emptied {src} (ctx={ctx}); contexts={sorted(df['context'].unique())}")
    sub.to_csv(dst, sep="\t", index=False)
    return f"tumor-only {len(sub)}/{len(df)} rows (context={ctx})"


def main() -> int:
    OUT.mkdir(exist_ok=True)
    copied, missing = [], []
    for label, desc, src_fn, dst_fn, tumor_only in SPECS:
        for L, cfg, ctx in LINEAGES:
            src = src_fn(cfg, ctx)
            dst = OUT / dst_fn(L)
            if src.exists():
                note = _emit(src, dst, tumor_only, ctx)
                copied.append((label, L, dst.name)); print(f"  [ok] {dst.name} ({note})")
            else:
                missing.append((label, L, str(src))); print(f"  [MISSING] {src}")
    # Suppl. Table S1 — data/code availability (a static file maintained in supplementary/).
    if (OUT / "SupplTable_S1_data_code_availability.md").exists():
        copied.append(("Suppl. Table S1", "-", "SupplTable_S1_data_code_availability.md"))

    readme = ["# Figure 7 — Supplementary materials (collected)\n",
              "Tumor-only scope. Generated by collect_supplementary.py. The S2 ladder and "
              "S4 provenance are filtered to the tumor context (NK Tang_Tumor, CD8 CD8_TIL).\n",
              "| File | Suppl. label | Lineage |", "|---|---|---|"]
    for label, L, name in copied:
        readme.append(f"| {name} | {label} | {L} |")
    (OUT / "README.md").write_text("\n".join(readme) + "\n", encoding="utf-8")

    print(f"\ncollected {len(copied)} files into {OUT}")
    if missing:
        print(f"MISSING ({len(missing)}):")
        for label, L, src in missing:
            print(f"  {label} [{L}]: {src}")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
